--- 
title: "Modelling lucerne growth and development under dryland conditions"
author: "Jian (AKA Frank) Liu"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
---

# What is this book for? {.unnumbered}

This book is a supplementary material for my master studying on 
the Agricultural Production Systems sIMulator next generation ([APSIMX](https://apsimnextgeneration.netlify.app/)).

- Why a book? 

1. I want to document the rational about the critical decision I made along the way.
At least in a code format so that I may recall in the future.  
2. Looks nice and easy to share with others.  
3. Github is free to host it.

- About the masters project 

The project aims to understand [Lucerne or Alfalfa](https://en.wikipedia.org/wiki/Alfalfa) 
performance under water deficit conditions in New Zealand and seek alternative 
ways for parameterising the APSIMx-Lucerne model. 

- About me

I'm a Data Scientist work in a reseach insititute called [Plant and Food Research](https://www.plantandfood.com/en-nz/) 
in New Zealand. I am also doing my master thesis at [Lincoln University](https://www.lincoln.ac.nz/) 
as a part-time student. The research topic I proposed covers three different
subjects: plant, soil and data science. 

## Acknowledgements {.unnumbered}

I wouldn't make this far without the following mentors:

[Prof. Derrick Moot](https://researchers.lincoln.ac.nz/derrick.moot)  
[Dr Hamish Brown](https://scholar.google.co.nz/citations?user=1y0v7J0AAAAJ&hl=en)  
[Dr Linley Jesson](https://scholar.google.co.nz/citations?hl=en&user=KxI3Y7QAAAAJ)  
[Dr Henry Chau](https://researchers.lincoln.ac.nz/henry.chau)  
[Dr Rogerio Cichota](https://www.journals.elsevier.com/agricultural-and-forest-meteorology/editorial-board/rogerio-cichota-phd)  
[Dr Edmar Teixeira](https://scholar.google.com.au/citations?user=FW4ucLEAAAAJ&hl=en)  
[Dr Yang, xiumei](https://www.researchgate.net/profile/Xiumei-Yang-2)  

## License {.unnumbered}
